name: Build and Publish to Docker Hub

on:
  push:
    branches:
      - main

env:
  DEPLOY_ACTION_REPO: ${{ github.repository }}
  DOCKER_REPOSITORY: ${{ github.repository }}
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "BUILD_DATE=$(date '+%Y%m%d_%H%m%S')" >> $GITHUB_ENV
          echo "SHORT_HASH=${GITHUB_SHA::7}" >> $GITHUB_ENV
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
    
      - name: Build & Publish to Docker Hub
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          #push: true
          push: false
          tags: |
            ${{ env.DOCKER_REPOSITORY }}:latest
            ${{ env.DOCKER_REPOSITORY }}:${{ env.BUILD_DATE }}
            ${{ env.DOCKER_REPOSITORY }}:${{ env.SHORT_HASH }}
#  trigger_deploy:
#    runs-on: ubuntu-latest
#    needs:
#      - docker
#    steps:
#      - name: Trigger deploy workflow
#        uses: peter-evans/repository-dispatch@v3
#        with:
#          token: ${{ secrets.GH_PAT }}
#          repository: ${{ env.DEPLOY_ACTION_REPO }}
#          event-type: trigger_deploy
